### ISSUE TITLE
read access violation on CreateCalculator2

### ISSUE THREAD

**Issue by Spajed** [zodiacon/InterceptionDemo#1]
Hi, 
I'm trying to debug the project but when calling CreateCalculator2 I get the following exception:
Exception thrown: read access violation.
p->**** was 0xFFFFFFFFFFFFFFFF. occurred
this exception happens on :
return pIntManager->QueryInterface(ppCalculator);

changing the call in the client project from CreateCalculator2 to CreateCalculator works as excepted in part 1.

**Comment by zodiacon** [comment]
Did you manage to step through CreateCalculator2, or is the call itself throws the exception?

**Comment by zodiacon** [comment]
Oh, sorry, missed the last line.

**Comment by zodiacon** [comment]
Did you make sure the calls in between return a success HRESULT?

**Comment by Spajed** [comment]
Yes, everything returned success
>	CalculatorsSvr.dll!ATL::CComObjectRootBase::_Delegate(void * pv, const _GUID & iid, void * * ppvObject, unsigned __int64 dw) Line 2558
 	CalculatorsSvr.dll!ATL::AtlInternalQueryInterface(void * pThis, const ATL::_ATL_INTMAP_ENTRY * pEntries, const _GUID & iid, void * * ppvObject) Line 8316
 	CalculatorsSvr.dll!ATL::CComObjectRootBase::InternalQueryInterface(void * pThis, const ATL::_ATL_INTMAP_ENTRY * pEntries, const _GUID & iid, void * * ppvObject) Line 2480
 	CalculatorsSvr.dll!CCalculatorInterceptor::_InternalQueryInterface(const _GUID & iid, void * * ppvObject) Line 38
 	CalculatorsSvr.dll!ATL::CComObject<CCalculatorInterceptor>::QueryInterface(const _GUID & iid, void * * ppvObject) Line 2942
 	CalculatorsSvr.dll!ATL::CComObject<CCalculatorInterceptor>::QueryInterface<ICalculator>(ICalculator * * pp) Line 2948
 	CalculatorsSvr.dll!CCalculatorFactory::CreateCalculator2(ICalculator * * ppCalculator) Line 127
 	Client.exe!main() Line 15

I have added the callstack

**Comment by Spajed** [comment]
I only changed the sdk version from 10.0.16299.0 to 10.0.15063.0 in the project settings
could that be the difference?

**Comment by zodiacon** [comment]
Did you change for both server and client projects? It should not really matter, weird.

**Comment by Spajed** [comment]
Yes, I changed for both.
Debugging using IDA reveals the exception occurs on:
call    qword ptr [rax]
while the registers are 
![image](https://user-images.githubusercontent.com/16502332/37241726-8030cc68-2466-11e8-9306-c3435499dfa9.png)
the value at rax is:
![image](https://user-images.githubusercontent.com/16502332/37241731-ab6d4c1c-2466-11e8-9a60-5a322aefc715.png)

**Comment by zodiacon** [comment]
Send me a ZIP with the entire solution

**Comment by Spajed** [comment]
https://ufile.io/ggk2w
the zip contains the compiled code, which crashes.

**Comment by zodiacon** [comment]
Building the code (with SDK ver 14393) works just fine (I don't have 15603 on my machine).
I don't know why your compiled DLL crashes. I wanted to debug with source, but compiling the source runs just fine.

**Comment by Spajed** [comment]
Could you test the precompiled dll I provided?

**Comment by Spajed** [comment]
Or you already tested it?

**Comment by zodiacon** [comment]
I did and it crashes. But I can't really easily debug it.

**Comment by Spajed** [comment]
I managed to get the code to run!
switched from VS2017 to VS2015.
looks like a compiler bug?

**Comment by zodiacon** [comment]
Very weird... I use VS 2017. Maybe a different update?

**Comment by Spajed** [comment]
i have visual studio 2017 version 15.3.4 if it means anything.

**Comment by zodiacon** [comment]
I use the latest version 15.6.1. Perhaps upgrade and test again?

**Comment by Spajed** [comment]
i updated to 15.6.1 and it fixed the problem
